
project_id = "hntgzgrlyfhojcaofbjv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 14

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://c18e16cb-e636-48a9-8108-3bd58a695608.lovableproject.com"
additional_redirect_urls = [
  "https://c18e16cb-e636-48a9-8108-3bd58a695608.lovableproject.com",
  "https://c18e16cb-e636-48a9-8108-3bd58a695608.lovableproject.com/auth",
  "https://c18e16cb-e636-48a9-8108-3bd58a695608.lovableproject.com/auth?type=recovery",
  "http://localhost:5173",
  "http://localhost:5173/auth",
  "http://localhost:5173/auth?type=recovery",
  "http://localhost:3000",
  "http://localhost:3000/auth",
  "http://localhost:3000/auth?type=recovery",
  "http://127.0.0.1:5173",
  "http://127.0.0.1:5173/auth",
  "http://127.0.0.1:5173/auth?type=recovery",
  "http://127.0.0.1:3000",
  "http://127.0.0.1:3000/auth",
  "http://127.0.0.1:3000/auth?type=recovery"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""
