import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
import { Home, Settings, Bell, PieChart, UserPlus, CalendarPlus, Users, Calendar, BarChart2, Loader2, Send, Check, LogOut, ChevronDown, ChevronUp, Share2, FileEdit, Clock, AlertCircle, FileText, Eye, Plus, Target, ClipboardCheck, BookOpen, Trophy } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { ScrollArea } from "@/components/ui/scroll-area";
import { supabase } from '@/lib/supabase';
import { useToast } from '@/hooks/use-toast';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { format, startOfMonth, endOfMonth, subMonths, isBefore, isAfter, isSameDay, isPast, formatDistance } from 'date-fns';
import { he } from 'date-fns/locale';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { SessionSummaryForm } from "@/components/session/SessionSummaryForm";
import { Calendar as CalendarComponent } from '@/components/calendar/Calendar';
import { Link } from 'react-router-dom';
import { Wrench } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Tool } from '@/types/tool';
import AllMeetingSummaries from './AllMeetingSummaries';
import { SessionFormDialog } from '@/components/sessions/SessionFormDialog';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Film } from 'lucide-react';
import { AdminMessageForm } from '@/components/admin/AdminMessageForm';
import { LandingPageDialog } from "@/components/landing-page/LandingPageDialog";
import { ClipboardList } from 'lucide-react';

interface LastSessionSummary {
  id: string;
  created_at: string;
  summary_text: string;
  achieved_goals: string[];
  future_goals: string[];
  progress_rating: number;
  next_session_focus: string;
  additional_notes?: string;
  session: {
    id: string;
    session_date: string;
    player: {
      id: string;
      full_name: string;
    } | null;
  };
}

interface Player {
  id: string;
  full_name: string;
  email: string;
  phone: string;
  birthdate: string;
  city: string;
  club: string;
  year_group: string;
  sport_field: string;
  injuries: string;
  parent_name: string;
  parent_phone: string;
  parent_email: string;
  notes: string;
  registration_link_id: string | null;
  registration_timestamp: string | null;
  coach_id: string;
}

interface UpcomingSession {
  id: string;
  created_at: string;
  session_date: string;
  start_time: string;
  end_time: string;
  location: string;
  player_id: string;
  coach_id: string;
  notes: string | null;
  is_confirmed: boolean;
  player: Player | null;
}

const DashboardCoach: React.FC = () => {
  const [coach, setCoach] = useState<any>(null);
  const [playersCount, setPlayersCount] = useState<number>(0);
  const [upcomingSessions, setUpcomingSessions] = useState<UpcomingSession[]>([]);
  const [lastSessionSummary, setLastSessionSummary] = useState<LastSessionSummary | null>(null);
  const [isAlertDialogOpen, setIsAlertDialogOpen] = useState(false);
  const [isLandingPageDialogOpen, setIsLandingPageDialogOpen] = useState(false);
  const [isSessionFormDialogOpen, setIsSessionFormDialogOpen] = useState(false);
  const [selectedSessionDate, setSelectedSessionDate] = useState<Date | undefined>(undefined);
  const [activeTab, setActiveTab] = useState('home');
  const [isCollapsibleOpen, setIsCollapsibleOpen] = useState(false);
  const [isCollapsibleOpen2, setIsCollapsibleOpen2] = useState(false);
  const [isCollapsibleOpen3, setIsCollapsibleOpen3] = useState(false);
  const [isCollapsibleOpen4, setIsCollapsibleOpen4] = useState(false);
  const [isCollapsibleOpen5, setIsCollapsibleOpen5] = useState(false);
  const [isCollapsibleOpen6, setIsCollapsibleOpen6] = useState(false);
  const [isCollapsibleOpen7, setIsCollapsibleOpen7] = useState(false);
  const [isCollapsibleOpen8, setIsCollapsibleOpen8] = useState(false);
  const [isCollapsibleOpen9, setIsCollapsibleOpen9] = useState(false);
  const [isCollapsibleOpen10, setIsCollapsibleOpen10] = useState(false);
  const [isCollapsibleOpen11, setIsCollapsibleOpen11] = useState(false);
  const [isCollapsibleOpen12, setIsCollapsibleOpen12] = useState(false);
  const [isCollapsibleOpen13, setIsCollapsibleOpen13] = useState(false);
  const [isCollapsibleOpen14, setIsCollapsibleOpen14] = useState(false);
  const [isCollapsibleOpen15, setIsCollapsibleOpen15] = useState(false);
  const [isCollapsibleOpen16, setIsCollapsibleOpen16] = useState(false);
  const [isCollapsibleOpen17, setIsCollapsibleOpen17] = useState(false);
  const [isCollapsibleOpen18, setIsCollapsibleOpen18] = useState(false);
  const [isCollapsibleOpen19, setIsCollapsibleOpen19] = useState(false);
  const [isCollapsibleOpen20, setIsCollapsibleOpen20] = useState(false);
  const [isCollapsibleOpen21, setIsCollapsibleOpen21] = useState(false);
  const [isCollapsibleOpen22, setIsCollapsibleOpen22] = useState(false);
  const [isCollapsibleOpen23, setIsCollapsibleOpen23] = useState(false);
  const [isCollapsibleOpen24, setIsCollapsibleOpen24] = useState(false);
  const [isCollapsibleOpen25, setIsCollapsibleOpen25] = useState(false);
  const [isCollapsibleOpen26, setIsCollapsibleOpen26] = useState(false);
  const [isCollapsibleOpen27, setIsCollapsibleOpen27] = useState(false);
  const [isCollapsibleOpen28, setIsCollapsibleOpen28] = useState(false);
  const [isCollapsibleOpen29, setIsCollapsibleOpen29] = useState(false);
  const [isCollapsibleOpen30, setIsCollapsibleOpen30] = useState(false);
  const [isCollapsibleOpen31, setIsCollapsibleOpen31] = useState(false);
  const [isCollapsibleOpen32, setIsCollapsibleOpen32] = useState(false);
  const [isCollapsibleOpen33, setIsCollapsibleOpen33] = useState(false);
  const [isCollapsibleOpen34, setIsCollapsibleOpen34] = useState(false);
  const [isCollapsibleOpen35, setIsCollapsibleOpen35] = useState(false);
  const [isCollapsibleOpen36, setIsCollapsibleOpen36] = useState(false);
  const [isCollapsibleOpen37, setIsCollapsibleOpen37] = useState(false);
  const [isCollapsibleOpen38, setIsCollapsibleOpen38] = useState(false);
  const [isCollapsibleOpen39, setIsCollapsibleOpen39] = useState(false);
  const [isCollapsibleOpen40, setIsCollapsibleOpen40] = useState(false);
  const [isCollapsibleOpen41, setIsCollapsibleOpen41] = useState(false);
  const [isCollapsibleOpen42, setIsCollapsibleOpen42] = useState(false);
  const [isCollapsibleOpen43, setIsCollapsibleOpen43] = useState(false);
  const [isCollapsibleOpen44, setIsCollapsibleOpen44] = useState(false);
  const [isCollapsibleOpen45, setIsCollapsibleOpen45] = useState(false);
  const [isCollapsibleOpen46, setIsCollapsibleOpen46] = useState(false);
  const [isCollapsibleOpen47, setIsCollapsibleOpen47] = useState(false);
  const [isCollapsibleOpen48, setIsCollapsibleOpen48] = useState(false);
  const [isCollapsibleOpen49, setIsCollapsibleOpen49] = useState(false);
  const [isCollapsibleOpen50, setIsCollapsibleOpen50] = useState(false);
  const [isCollapsibleOpen51, setIsCollapsibleOpen51] = useState(false);
  const [isCollapsibleOpen52, setIsCollapsibleOpen52] = useState(false);
  const [isCollapsibleOpen53, setIsCollapsibleOpen53] = useState(false);
  const [isCollapsibleOpen54, setIsCollapsibleOpen54] = useState(false);
  const [isCollapsibleOpen55, setIsCollapsibleOpen55] = useState(false);
  const [isCollapsibleOpen56, setIsCollapsibleOpen56] = useState(false);
  const [isCollapsibleOpen57, setIsCollapsibleOpen57] = useState(false);
  const [isCollapsibleOpen58, setIsCollapsibleOpen58] = useState(false);
  const [isCollapsibleOpen59, setIsCollapsibleOpen59] = useState(false);
  const [isCollapsibleOpen60, setIsCollapsibleOpen60] = useState(false);
  const [isCollapsibleOpen61, setIsCollapsibleOpen61] = useState(false);
  const [isCollapsibleOpen62, setIsCollapsibleOpen62] = useState(false);
  const [isCollapsibleOpen63, setIsCollapsibleOpen63] = useState(false);
  const [isCollapsibleOpen64, setIsCollapsibleOpen64] = useState(false);
  const [isCollapsibleOpen65, setIsCollapsibleOpen65] = useState(false);
  const [isCollapsibleOpen66, setIsCollapsibleOpen66] = useState(false);
  const [isCollapsibleOpen67, setIsCollapsibleOpen67] = useState(false);
  const [isCollapsibleOpen68, setIsCollapsibleOpen68] = useState(false);
  const [isCollapsibleOpen69, setIsCollapsibleOpen69] = useState(false);
  const [isCollapsibleOpen70, setIsCollapsibleOpen70] = useState(false);
  const [isCollapsibleOpen71, setIsCollapsibleOpen71] = useState(false);
  const [isCollapsibleOpen72, setIsCollapsibleOpen72] = useState(false);
  const [isCollapsibleOpen73, setIsCollapsibleOpen73] = useState(false);
  const [isCollapsibleOpen74, setIsCollapsibleOpen74] = useState(false);
  const [isCollapsibleOpen75, setIsCollapsibleOpen75] = useState(false);
  const [isCollapsibleOpen76, setIsCollapsibleOpen76] = useState(false);
  const [isCollapsibleOpen77, setIsCollapsibleOpen77] = useState(false);
  const [isCollapsibleOpen78, setIsCollapsibleOpen78] = useState(false);
  const [isCollapsibleOpen79, setIsCollapsibleOpen79] = useState(false);
  const [isCollapsibleOpen80, setIsCollapsibleOpen80] = useState(false);
  const [isCollapsibleOpen81, setIsCollapsibleOpen81] = useState(false);
  const [isCollapsibleOpen82, setIsCollapsibleOpen82] = useState(false);
  const [isCollapsibleOpen83, setIsCollapsibleOpen83] = useState(false);
  const [isCollapsibleOpen84, setIsCollapsibleOpen84] = useState(false);
  const [isCollapsibleOpen85, setIsCollapsibleOpen85] = useState(false);
  const [isCollapsibleOpen86, setIsCollapsibleOpen86] = useState(false);
  const [isCollapsibleOpen87, setIsCollapsibleOpen87] = useState(false);
  const [isCollapsibleOpen88, setIsCollapsibleOpen88] = useState(false);
  const [isCollapsibleOpen89, setIsCollapsibleOpen89] = useState(false);
  const [isCollapsibleOpen90, setIsCollapsibleOpen90] = useState(false);
  const [isCollapsibleOpen91, setIsCollapsibleOpen91] = useState(false);
  const [isCollapsibleOpen92, setIsCollapsibleOpen92] = useState(false);
  const [isCollapsibleOpen93, setIsCollapsibleOpen93] = useState(false);
  const [isCollapsibleOpen94, setIsCollapsibleOpen94] = useState(false);
  const [isCollapsibleOpen95, setIsCollapsibleOpen95] = useState(false);
  const [isCollapsibleOpen96, setIsCollapsibleOpen96] = useState(false);
  const [isCollapsibleOpen97, setIsCollapsibleOpen97] = useState(false);
  const [isCollapsibleOpen98, setIsCollapsibleOpen98] = useState(false);
  const [isCollapsibleOpen99, setIsCollapsibleOpen99] = useState(false);
  const [isCollapsibleOpen100, setIsCollapsibleOpen100] = useState(false);
  const [isCollapsibleOpen101, setIsCollapsibleOpen101] = useState(false);
  const [isCollapsibleOpen102, setIsCollapsibleOpen102] = useState(false);
  const [isCollapsibleOpen103, setIsCollapsibleOpen103] = useState(false);
  const [isCollapsibleOpen104, setIsCollapsibleOpen104] = useState(false);
  const [isCollapsibleOpen105, setIsCollapsibleOpen105] = useState(false);
  const [isCollapsibleOpen106, setIsCollapsibleOpen106] = useState(false);
  const [isCollapsibleOpen107, setIsCollapsibleOpen107] = useState(false);
  const [isCollapsibleOpen108, setIsCollapsibleOpen108] = useState(false);
  const [isCollapsibleOpen109, setIsCollapsibleOpen109] = useState(false);
  const [isCollapsibleOpen110, setIsCollapsibleOpen110] = useState(false);
  const [isCollapsibleOpen111, setIsCollapsibleOpen111] = useState(false);
  const [isCollapsibleOpen112, setIsCollapsibleOpen112] = useState(false);
  const [isCollapsibleOpen113, setIsCollapsibleOpen113] = useState(false);
  const [isCollapsibleOpen114, setIsCollapsibleOpen114] = useState(false);
  const [isCollapsibleOpen115, setIsCollapsibleOpen115] = useState(false);
  const [isCollapsibleOpen116, setIsCollapsibleOpen116] = useState(false);
  const [isCollapsibleOpen117, setIsCollapsibleOpen117] = useState(false);
  const [isCollapsibleOpen118, setIsCollapsibleOpen118] = useState(false);
  const [isCollapsibleOpen119, setIsCollapsibleOpen119] = useState(false);
  const [isCollapsibleOpen120, setIsCollapsibleOpen120] = useState(false);
  const [isCollapsibleOpen121, setIsCollapsibleOpen121] = useState(false);
  const [isCollapsibleOpen122, setIsCollapsibleOpen122] = useState(false);
  const [isCollapsibleOpen123, setIsCollapsibleOpen123] = useState(false);
  const [isCollapsibleOpen124, setIsCollapsibleOpen124] = useState(false);
  const [isCollapsibleOpen125, setIsCollapsibleOpen125] = useState(false);
  const [isCollapsibleOpen126, setIsCollapsibleOpen126] = useState(false);
  const [isCollapsibleOpen127, setIsCollapsibleOpen127] = useState(false);
  const [isCollapsibleOpen128, setIsCollapsibleOpen128] = useState(false);
  const [isCollapsibleOpen129, setIsCollapsibleOpen129] = useState(false);
  const [isCollapsibleOpen130, setIsCollapsibleOpen130] = useState(false);
  const [isCollapsibleOpen131, setIsCollapsibleOpen131] = useState(false);
  const [isCollapsibleOpen132, setIsCollapsibleOpen132] = useState(false);
  const [isCollapsibleOpen133, setIsCollapsibleOpen133] = useState(false);
  const [isCollapsibleOpen134, setIsCollapsibleOpen134] = useState(false);
  const [isCollapsibleOpen135, setIsCollapsibleOpen135] = useState(false);
  const [isCollapsibleOpen136, setIsCollapsibleOpen136] = useState(false);
  const [isCollapsibleOpen137, setIsCollapsibleOpen137] = useState(false);
  const [isCollapsibleOpen138, setIsCollapsibleOpen138] = useState(false);
  const [isCollapsibleOpen139, setIsCollapsibleOpen139] = useState(false);
  const [isCollapsibleOpen140, setIsCollapsibleOpen140] = useState(false);
  const [isCollapsibleOpen141, setIsCollapsibleOpen141] = useState(false);
  const [isCollapsibleOpen142, setIsCollapsibleOpen142] = useState(false);
  const [isCollapsibleOpen143, setIsCollapsibleOpen143] = useState(false);
  const [isCollapsibleOpen144, setIsCollapsibleOpen144] = useState(false);
  const [isCollapsibleOpen145, setIsCollapsibleOpen145] = useState(false);
  const [isCollapsibleOpen146, setIsCollapsibleOpen146] = useState(false);
  const [isCollapsibleOpen147, setIsCollapsibleOpen147] = useState(false);
  const [isCollapsibleOpen148, setIsCollapsibleOpen148] = useState(false);
  const [isCollapsibleOpen149, setIsCollapsibleOpen149] = useState(false);
  const [isCollapsibleOpen150, setIsCollapsibleOpen150] = useState(false);
  const [isCollapsibleOpen151, setIsCollapsibleOpen151] = useState(false);
  const [isCollapsibleOpen152, setIsCollapsibleOpen152] = useState(false);
  const [isCollapsibleOpen153, setIsCollapsibleOpen153] = useState(false);
  const [isCollapsibleOpen154, setIsCollapsibleOpen154] = useState(false);
  const [isCollapsibleOpen155, setIsCollapsibleOpen155] = useState(false);
  const [isCollapsibleOpen156, setIsCollapsibleOpen156] = useState(false);
  const [isCollapsibleOpen157, setIsCollapsibleOpen157] = useState(false);
  const [isCollapsibleOpen158, setIsCollapsibleOpen158] = useState(false);
  const [isCollapsibleOpen159, setIsCollapsibleOpen159] = useState(false);
  const [isCollapsibleOpen160, setIsCollapsibleOpen160] = useState(false);
  const [isCollapsibleOpen161, setIsCollapsibleOpen161] = useState(false);
  const [isCollapsibleOpen162, setIsCollapsibleOpen162] = useState(false);
  const [isCollapsibleOpen163, setIsCollapsibleOpen163] = useState(false);
  const [isCollapsibleOpen164, setIsCollapsibleOpen164] = useState(false);
  const [isCollapsibleOpen165, setIsCollapsibleOpen165] = useState(false);
  const [isCollapsibleOpen166, setIsCollapsibleOpen166] = useState(false);
  const [isCollapsibleOpen167, setIsCollapsibleOpen167] = useState(false);
  const [isCollapsibleOpen168, setIsCollapsibleOpen168] = useState(false);
  const [isCollapsibleOpen169, setIsCollapsibleOpen169] = useState(false);
  const [isCollapsibleOpen170, setIsCollapsibleOpen170] = useState(false);
  const [isCollapsibleOpen171, setIsCollapsibleOpen171] = useState(false);
  const [isCollapsibleOpen172, setIsCollapsibleOpen172] = useState(false);
  const [isCollapsibleOpen173, setIsCollapsibleOpen173] = useState(false);
  const [isCollapsibleOpen174, setIsCollapsibleOpen174] = useState(false);
  const [isCollapsibleOpen175, setIsCollapsibleOpen175] = useState(false);
  const [isCollapsibleOpen176, setIsCollapsibleOpen176] = useState(false);
  const [isCollapsibleOpen177, setIsCollapsibleOpen177] = useState(false);
  const [isCollapsibleOpen178, setIsCollapsibleOpen178] = useState(false);
  const [isCollapsibleOpen179, setIsCollapsibleOpen179] = useState(false);
  const [isCollapsibleOpen180, setIsCollapsibleOpen180] = useState(false);
  const [isCollapsibleOpen181, setIsCollapsibleOpen181] = useState(false);
  const [isCollapsibleOpen182, setIsCollapsibleOpen182] = useState(false);
  const [isCollapsibleOpen183, setIsCollapsibleOpen183] = useState(false);
  const [isCollapsibleOpen184, setIsCollapsibleOpen184] = useState(false);
  const [isCollapsibleOpen185, setIsCollapsibleOpen185] = useState(false);
  const [isCollapsibleOpen186, setIsCollapsibleOpen186] = useState(false);
  const [isCollapsibleOpen187, setIsCollapsibleOpen187] = useState(false);
  const [isCollapsibleOpen188, setIsCollapsibleOpen188] = useState(false);
  const [isCollapsibleOpen189, setIsCollapsibleOpen189] = useState(false);
  const [isCollapsibleOpen190, setIsCollapsibleOpen190] = useState(false);
  const [isCollapsibleOpen191, setIsCollapsibleOpen191] = useState(false);
  const [isCollapsibleOpen192, setIsCollapsibleOpen192] = useState(false);
  const [isCollapsibleOpen193, setIsCollapsibleOpen193] = useState(false);
  const [isCollapsibleOpen194, setIsCollapsibleOpen194] = useState(false);
  const [isCollapsibleOpen195, setIsCollapsibleOpen195] = useState(false);
  const [isCollapsibleOpen196, setIsCollapsibleOpen196] = useState(false);
  const [isCollapsibleOpen197, setIsCollapsibleOpen197] = useState(false);
  const [isCollapsibleOpen198, setIsCollapsibleOpen198] = useState(false);
  const [isCollapsibleOpen199, setIsCollapsibleOpen199] = useState(false);
  const [isCollapsibleOpen200, setIsCollapsibleOpen200] = useState(false);
  const [isCollapsibleOpen201, setIsCollapsibleOpen201] = useState(false);
  const [isCollapsibleOpen202, setIsCollapsibleOpen202] = useState(false);
  const [isCollapsibleOpen203, setIsCollapsibleOpen203] = useState(false);
  const [isCollapsibleOpen204, setIsCollapsibleOpen204] = useState(false);
  const [isCollapsibleOpen205, setIsCollapsibleOpen205] = useState(false);
  const [isCollapsibleOpen206, setIsCollapsibleOpen206] = useState(false);
  const [isCollapsibleOpen207, setIsCollapsibleOpen207] = useState(false);
  const [isCollapsibleOpen208, setIsCollapsibleOpen208] = useState(false);
  const [isCollapsibleOpen209, setIsCollapsibleOpen209] = useState(false);
  const [isCollapsibleOpen210, setIsCollapsibleOpen210] = useState(false);
  const [isCollapsibleOpen211, setIsCollapsibleOpen211] = useState(false);
  const [isCollapsibleOpen212, setIsCollapsibleOpen212] = useState(false);
  const [isCollapsibleOpen213, setIsCollapsibleOpen213] = useState(false);
  const [isCollapsibleOpen214, setIsCollapsibleOpen214] = useState(false);
  const [isCollapsibleOpen215, setIsCollapsibleOpen215] = useState(false);
  const [isCollapsibleOpen216, setIsCollapsibleOpen216] = useState(false);
  const [isCollapsibleOpen217, setIsCollapsibleOpen217] = useState(false);
  const [isCollapsibleOpen218, setIsCollapsibleOpen218] = useState(false);
  const [isCollapsibleOpen219, setIsCollapsibleOpen219] = useState(false);
  const [isCollapsibleOpen220, setIsCollapsibleOpen220] = useState(false);
  const [isCollapsibleOpen221, setIsCollapsibleOpen221] = useState(false);
  const [isCollapsibleOpen222, setIsCollapsibleOpen222] = useState(false);
  const [isCollapsibleOpen223, setIsCollapsibleOpen223] = useState(false);
  const [isCollapsibleOpen224, setIsCollapsibleOpen224] = useState(false);
  const [isCollapsibleOpen225, setIsCollapsibleOpen225] = useState(false);
  const [isCollapsibleOpen226, setIsCollapsibleOpen226] = useState(false);
  const [isCollapsibleOpen227, setIsCollapsibleOpen227] = useState(false);
  const [isCollapsibleOpen228, setIsCollapsibleOpen228] = useState(false);
  const [isCollapsibleOpen229, setIsCollapsibleOpen229] = useState(false);
  const [isCollapsibleOpen230, setIsCollapsibleOpen230] = useState(false);
  const [isCollapsibleOpen231, setIsCollapsibleOpen231] = useState(false);
  const [isCollapsibleOpen232, setIsCollapsibleOpen232] = useState(false);
  const [isCollapsibleOpen233, setIsCollapsibleOpen233] = useState(false);
  const [isCollapsibleOpen234, setIsCollapsibleOpen234] = useState(false);
  const [isCollapsibleOpen235, setIsCollapsibleOpen235] = useState(false);
  const [isCollapsibleOpen236, setIsCollapsibleOpen236] = useState(false);
  const [isCollapsibleOpen237, setIsCollapsibleOpen237] = useState(false);
  const [isCollapsibleOpen238, setIsCollapsibleOpen238] = useState(false);
  const [isCollapsibleOpen239, setIsCollapsibleOpen239] = useState(false);
  const [isCollapsibleOpen240, setIsCollapsibleOpen240] = useState(false);
  const [isCollapsibleOpen241, setIsCollapsibleOpen241] = useState(false);
  const [isCollapsibleOpen242, setIsCollapsibleOpen242] = useState(false);
  const [isCollapsibleOpen243, setIsCollapsibleOpen243] = useState(false);
  const [isCollapsibleOpen244, setIsCollapsibleOpen244] = useState(false);
  const [isCollapsibleOpen245, setIsCollapsibleOpen245] = useState(false);
  const [isCollapsibleOpen246, setIsCollapsibleOpen246] = useState(false);
  const [isCollapsibleOpen247, setIsCollapsibleOpen247] = useState(false);
  const [isCollapsibleOpen248, setIsCollapsibleOpen248] = useState(false);
  const [isCollapsibleOpen249, setIsCollapsibleOpen249] = useState(false);
  const [isCollapsibleOpen250, setIsCollapsibleOpen250] = useState(false);
  const [isCollapsibleOpen251, setIsCollapsibleOpen251] = useState(false);
  const [isCollapsibleOpen252, setIsCollapsibleOpen252] = useState(false);
  const [isCollapsibleOpen253, setIsCollapsibleOpen253] = useState(false);
  const [isCollapsibleOpen254, setIsCollapsibleOpen254] = useState(false);
  const [isCollapsibleOpen255, setIsCollapsibleOpen255] = useState(false);
  const [isCollapsibleOpen256, setIsCollapsibleOpen256] = useState(false);
  const [isCollapsibleOpen257, setIsCollapsibleOpen257] = useState(false);
  const [isCollapsibleOpen258, setIsCollapsibleOpen258] = useState(false);
  const [isCollapsibleOpen259, setIsCollapsibleOpen259] = useState(false);
  const [isCollapsibleOpen260, setIsCollapsibleOpen260] = useState(false);
  const [isCollapsibleOpen261, setIsCollapsibleOpen261] = useState(false);
  const [isCollapsibleOpen262, setIsCollapsibleOpen262] = useState(false);
  const [isCollapsibleOpen263, setIsCollapsibleOpen263] = useState(false);
  const [isCollapsibleOpen264, setIsCollapsibleOpen264] = useState(false);
  const [isCollapsibleOpen265, setIsCollapsibleOpen265] = useState(false);
  const [isCollapsibleOpen266, setIsCollapsibleOpen266] = useState(false);
  const [isCollapsibleOpen267, setIsCollapsibleOpen267] = useState(false);
  const [isCollapsibleOpen268, setIsCollapsibleOpen268] = useState(false);
  const [isCollapsibleOpen269, setIsCollapsibleOpen269] = useState(false);
  const [isCollapsibleOpen270, setIsCollapsibleOpen270] = useState(false);
  const [isCollapsibleOpen271, setIsCollapsibleOpen271] = useState(false);
  const [isCollapsibleOpen272, setIsCollapsibleOpen272] = useState(false);
  const [isCollapsibleOpen273, setIsCollapsibleOpen273] = useState(false);
  const [isCollapsibleOpen274, setIsCollapsibleOpen274] = useState(false);
  const [isCollapsibleOpen275, setIsCollapsibleOpen275] = useState(false);
  const [isCollapsibleOpen276, setIsCollapsibleOpen276] = useState(false);
  const [isCollapsibleOpen277, setIsCollapsibleOpen277] = useState(false);
  const [isCollapsibleOpen278, setIsCollapsibleOpen278] = useState(false);
  const [isCollapsibleOpen279, setIsCollapsibleOpen279] = useState(false);
  const [isCollapsibleOpen280, setIsCollapsibleOpen280] = useState(false);
  const [isCollapsibleOpen281, setIsCollapsibleOpen281] = useState(false);
  const [isCollapsibleOpen282, setIsCollapsibleOpen282] = useState(false);
  const [isCollapsibleOpen283, setIsCollapsibleOpen283] = useState(false);
  const [isCollapsibleOpen284, setIsCollapsibleOpen284] = useState(false);
  const [isCollapsibleOpen285, setIsCollapsibleOpen285] = useState(false);
  const [isCollapsibleOpen286, setIsCollapsibleOpen286] = useState(false);
  const [isCollapsibleOpen287, setIsCollapsibleOpen287] = useState(false);
  const [isCollapsibleOpen288, setIsCollapsibleOpen288] = useState(false);
  const [isCollapsibleOpen289, setIsCollapsibleOpen289] = useState(false);
  const [isCollapsibleOpen290, setIsCollapsibleOpen290] = useState(false);
  const [isCollapsibleOpen291, setIsCollapsibleOpen291] = useState(false);
  const [isCollapsibleOpen292, setIsCollapsibleOpen292] = useState(false);
  const [isCollapsibleOpen
