import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
import { Home, Settings, Bell, PieChart, UserPlus, CalendarPlus, Users, Calendar, BarChart2, Loader2, Send, Check, LogOut, ChevronDown, ChevronUp, Share2, FileEdit, Clock, AlertCircle, FileText, Eye, Plus, Target, ClipboardCheck, BookOpen, Trophy, Menu, MessageCircle } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { ScrollArea } from "@/components/ui/scroll-area";
import { supabase } from '@/lib/supabase';
import { useToast } from '@/hooks/use-toast';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { format, startOfMonth, endOfMonth, subMonths, isBefore, isAfter, isSameDay, isPast, formatDistance } from 'date-fns';
import { he } from 'date-fns/locale';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { SessionSummaryForm } from "@/components/session/SessionSummaryForm";
import { Calendar as CalendarComponent } from '@/components/calendar/Calendar';
import { Link } from 'react-router-dom';
import { Wrench } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Tool } from '@/types/tool';
import AllMeetingSummaries from './AllMeetingSummaries';
import { SessionFormDialog } from '@/components/sessions/SessionFormDialog';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Film } from 'lucide-react';
import { AdminMessageForm } from '@/components/admin/AdminMessageForm';
import { LandingPageDialog } from "@/components/landing-page/LandingPageDialog";
import { ClipboardList } from 'lucide-react';
import { useIsMobile } from '@/hooks/use-mobile';
import { useScreenSize } from '@/hooks/use-screen-size';

const DashboardCoach = () => {
  const navigate = useNavigate();
  const [coach, setCoach] = useState(null);
  const [tools, setTools] = useState<Tool[]>([]);
  const [sessions, setSessions] = useState([]);
  const [upcomingSessions, setUpcomingSessions] = useState([]);
  const [playersCount, setPlayersCount] = useState(0);
  const [showAllTools, setShowAllTools] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [isNotificationsOpen, setIsNotificationsOpen] = useState(false);
  const [isShareOpen, setIsShareOpen] = useState(false);
  const [isProfileOpen, setIsProfileOpen] = useState(false);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isCollapsibleOpen, setIsCollapsibleOpen] = useState(false);
  const [isLandingPageDialogOpen, setIsLandingPageDialogOpen] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isNewSessionDialogOpen, setIsNewSessionDialogOpen] = useState(false);
  const [isAllSummariesOpen, setIsAllSummariesOpen] = useState(false);
  const [isNewMessageDialogOpen, setIsNewMessageDialogOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const [windowSize, setWindowSize] = useState({ width: 0, height: 0 });
  const [isAlertOpen, setIsAlertOpen] = useState(false);
  const [alertMessage, setAlertMessage] = useState('');
  const [alertTitle, setAlertTitle] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [events, setEvents] = useState([]);
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [currentMonth, setCurrentMonth] = useState(startOfMonth(new Date()));
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isSessionSummaryDialogOpen, setIsSessionSummaryDialogOpen] = useState(false);
  const [sessionForSummary, setSessionForSummary] = useState(null);
  const [isSessionFormDialogOpen, setIsSessionFormDialogOpen] = useState(false);
  const [isToolDialogOpen, setIsToolDialogOpen] = useState(false);
  const [selectedTool, setSelectedTool] = useState(null);
  const [isToolEditMode, setIsToolEditMode] = useState(false);
  const [isToolDeleteAlertOpen, setIsToolDeleteAlertOpen] = useState(false);
  const [toolToDelete, setToolToDelete] = useState(null);
  const [isToolShareDialogOpen, setIsToolShareDialogOpen] = useState(false);
  const [toolToShare, setToolToShare] = useState(null);
  const [isToolDetailsDialogOpen, setIsToolDetailsDialogOpen] = useState(false);
  const [toolForDetails, setToolForDetails] = useState(null);
  const [isToolCreateDialogOpen, setIsToolCreateDialogOpen] = useState(false);
  const [isToolEditDialogOpen, setIsToolEditDialogOpen] = useState(false);
  const [isToolDeleteDialogOpen, setIsToolDeleteDialogOpen] = useState(false);
  const [isToolDuplicateDialogOpen, setIsToolDuplicateDialogOpen] = useState(false);
  const [toolToDuplicate, setToolToDuplicate] = useState(null);
  const [isToolDuplicateAlertOpen, setIsToolDuplicateAlertOpen] = useState(false);
  const [isToolDuplicateConfirmOpen, setIsToolDuplicateConfirmOpen] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen, setIsToolDuplicateConfirmDialogAlertDialogOpen] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen2, setIsToolDuplicateConfirmDialogAlertDialogOpen2] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen3, setIsToolDuplicateConfirmDialogAlertDialogOpen3] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen4, setIsToolDuplicateConfirmDialogAlertDialogOpen4] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen5, setIsToolDuplicateConfirmDialogAlertDialogOpen5] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen6, setIsToolDuplicateConfirmDialogAlertDialogOpen6] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen7, setIsToolDuplicateConfirmDialogAlertDialogOpen7] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen8, setIsToolDuplicateConfirmDialogAlertDialogOpen8] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen9, setIsToolDuplicateConfirmDialogAlertDialogOpen9] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen10, setIsToolDuplicateConfirmDialogAlertDialogOpen10] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen11, setIsToolDuplicateConfirmDialogAlertDialogOpen11] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen12, setIsToolDuplicateConfirmDialogAlertDialogOpen12] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen13, setIsToolDuplicateConfirmDialogAlertDialogOpen13] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen14, setIsToolDuplicateConfirmDialogAlertDialogOpen14] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen15, setIsToolDuplicateConfirmDialogAlertDialogOpen15] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen16, setIsToolDuplicateConfirmDialogAlertDialogOpen16] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen17, setIsToolDuplicateConfirmDialogAlertDialogOpen17] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen18, setIsToolDuplicateConfirmDialogAlertDialogOpen18] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen19, setIsToolDuplicateConfirmDialogAlertDialogOpen19] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen20, setIsToolDuplicateConfirmDialogAlertDialogOpen20] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen21, setIsToolDuplicateConfirmDialogAlertDialogOpen21] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen22, setIsToolDuplicateConfirmDialogAlertDialogOpen22] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen23, setIsToolDuplicateConfirmDialogAlertDialogOpen23] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen24, setIsToolDuplicateConfirmDialogAlertDialogOpen24] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen25, setIsToolDuplicateConfirmDialogAlertDialogOpen25] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen26, setIsToolDuplicateConfirmDialogAlertDialogOpen26] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen27, setIsToolDuplicateConfirmDialogAlertDialogOpen27] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen28, setIsToolDuplicateConfirmDialogAlertDialogOpen28] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen29, setIsToolDuplicateConfirmDialogAlertDialogOpen29] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen30, setIsToolDuplicateConfirmDialogAlertDialogOpen30] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen31, setIsToolDuplicateConfirmDialogAlertDialogOpen31] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen32, setIsToolDuplicateConfirmDialogAlertDialogOpen32] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen33, setIsToolDuplicateConfirmDialogAlertDialogOpen33] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen34, setIsToolDuplicateConfirmDialogAlertDialogOpen34] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen35, setIsToolDuplicateConfirmDialogAlertDialogOpen35] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen36, setIsToolDuplicateConfirmDialogAlertDialogOpen36] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen37, setIsToolDuplicateConfirmDialogAlertDialogOpen37] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen38, setIsToolDuplicateConfirmDialogAlertDialogOpen38] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen39, setIsToolDuplicateConfirmDialogAlertDialogOpen39] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen40, setIsToolDuplicateConfirmDialogAlertDialogOpen40] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen41, setIsToolDuplicateConfirmDialogAlertDialogOpen41] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen42, setIsToolDuplicateConfirmDialogAlertDialogOpen42] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen43, setIsToolDuplicateConfirmDialogAlertDialogOpen43] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen44, setIsToolDuplicateConfirmDialogAlertDialogOpen44] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen45, setIsToolDuplicateConfirmDialogAlertDialogOpen45] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen46, setIsToolDuplicateConfirmDialogAlertDialogOpen46] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen47, setIsToolDuplicateConfirmDialogAlertDialogOpen47] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen48, setIsToolDuplicateConfirmDialogAlertDialogOpen48] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen49, setIsToolDuplicateConfirmDialogAlertDialogOpen49] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen50, setIsToolDuplicateConfirmDialogAlertDialogOpen50] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen51, setIsToolDuplicateConfirmDialogAlertDialogOpen51] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen52, setIsToolDuplicateConfirmDialogAlertDialogOpen52] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen53, setIsToolDuplicateConfirmDialogAlertDialogOpen53] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen54, setIsToolDuplicateConfirmDialogAlertDialogOpen54] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen55, setIsToolDuplicateConfirmDialogAlertDialogOpen55] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen56, setIsToolDuplicateConfirmDialogAlertDialogOpen56] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen57, setIsToolDuplicateConfirmDialogAlertDialogOpen57] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen58, setIsToolDuplicateConfirmDialogAlertDialogOpen58] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen59, setIsToolDuplicateConfirmDialogAlertDialogOpen59] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen60, setIsToolDuplicateConfirmDialogAlertDialogOpen60] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen61, setIsToolDuplicateConfirmDialogAlertDialogOpen61] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen62, setIsToolDuplicateConfirmDialogAlertDialogOpen62] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen63, setIsToolDuplicateConfirmDialogAlertDialogOpen63] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen64, setIsToolDuplicateConfirmDialogAlertDialogOpen64] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen65, setIsToolDuplicateConfirmDialogAlertDialogOpen65] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen66, setIsToolDuplicateConfirmDialogAlertDialogOpen66] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen67, setIsToolDuplicateConfirmDialogAlertDialogOpen67] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen68, setIsToolDuplicateConfirmDialogAlertDialogOpen68] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen69, setIsToolDuplicateConfirmDialogAlertDialogOpen69] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen70, setIsToolDuplicateConfirmDialogAlertDialogOpen70] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen71, setIsToolDuplicateConfirmDialogAlertDialogOpen71] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen72, setIsToolDuplicateConfirmDialogAlertDialogOpen72] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen73, setIsToolDuplicateConfirmDialogAlertDialogOpen73] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen74, setIsToolDuplicateConfirmDialogAlertDialogOpen74] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen75, setIsToolDuplicateConfirmDialogAlertDialogOpen75] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen76, setIsToolDuplicateConfirmDialogAlertDialogOpen76] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen77, setIsToolDuplicateConfirmDialogAlertDialogOpen77] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen78, setIsToolDuplicateConfirmDialogAlertDialogOpen78] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen79, setIsToolDuplicateConfirmDialogAlertDialogOpen79] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen80, setIsToolDuplicateConfirmDialogAlertDialogOpen80] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen81, setIsToolDuplicateConfirmDialogAlertDialogOpen81] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen82, setIsToolDuplicateConfirmDialogAlertDialogOpen82] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen83, setIsToolDuplicateConfirmDialogAlertDialogOpen83] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen84, setIsToolDuplicateConfirmDialogAlertDialogOpen84] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen85, setIsToolDuplicateConfirmDialogAlertDialogOpen85] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen86, setIsToolDuplicateConfirmDialogAlertDialogOpen86] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen87, setIsToolDuplicateConfirmDialogAlertDialogOpen87] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen88, setIsToolDuplicateConfirmDialogAlertDialogOpen88] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen89, setIsToolDuplicateConfirmDialogAlertDialogOpen89] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen90, setIsToolDuplicateConfirmDialogAlertDialogOpen90] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen91, setIsToolDuplicateConfirmDialogAlertDialogOpen91] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen92, setIsToolDuplicateConfirmDialogAlertDialogOpen92] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen93, setIsToolDuplicateConfirmDialogAlertDialogOpen93] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen94, setIsToolDuplicateConfirmDialogAlertDialogOpen94] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen95, setIsToolDuplicateConfirmDialogAlertDialogOpen95] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen96, setIsToolDuplicateConfirmDialogAlertDialogOpen96] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen97, setIsToolDuplicateConfirmDialogAlertDialogOpen97] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen98, setIsToolDuplicateConfirmDialogAlertDialogOpen98] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen99, setIsToolDuplicateConfirmDialogAlertDialogOpen99] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen100, setIsToolDuplicateConfirmDialogAlertDialogOpen100] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen101, setIsToolDuplicateConfirmDialogAlertDialogOpen101] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen102, setIsToolDuplicateConfirmDialogAlertDialogOpen102] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen103, setIsToolDuplicateConfirmDialogAlertDialogOpen103] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen104, setIsToolDuplicateConfirmDialogAlertDialogOpen104] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen105, setIsToolDuplicateConfirmDialogAlertDialogOpen105] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen106, setIsToolDuplicateConfirmDialogAlertDialogOpen106] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen107, setIsToolDuplicateConfirmDialogAlertDialogOpen107] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen108, setIsToolDuplicateConfirmDialogAlertDialogOpen108] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen109, setIsToolDuplicateConfirmDialogAlertDialogOpen109] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen110, setIsToolDuplicateConfirmDialogAlertDialogOpen110] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen111, setIsToolDuplicateConfirmDialogAlertDialogOpen111] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen112, setIsToolDuplicateConfirmDialogAlertDialogOpen112] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen113, setIsToolDuplicateConfirmDialogAlertDialogOpen113] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen114, setIsToolDuplicateConfirmDialogAlertDialogOpen114] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen115, setIsToolDuplicateConfirmDialogAlertDialogOpen115] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen116, setIsToolDuplicateConfirmDialogAlertDialogOpen116] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen117, setIsToolDuplicateConfirmDialogAlertDialogOpen117] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen118, setIsToolDuplicateConfirmDialogAlertDialogOpen118] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen119, setIsToolDuplicateConfirmDialogAlertDialogOpen119] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen120, setIsToolDuplicateConfirmDialogAlertDialogOpen120] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen121, setIsToolDuplicateConfirmDialogAlertDialogOpen121] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen122, setIsToolDuplicateConfirmDialogAlertDialogOpen122] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen123, setIsToolDuplicateConfirmDialogAlertDialogOpen123] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen124, setIsToolDuplicateConfirmDialogAlertDialogOpen124] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen125, setIsToolDuplicateConfirmDialogAlertDialogOpen125] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen126, setIsToolDuplicateConfirmDialogAlertDialogOpen126] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen127, setIsToolDuplicateConfirmDialogAlertDialogOpen127] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen128, setIsToolDuplicateConfirmDialogAlertDialogOpen128] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen129, setIsToolDuplicateConfirmDialogAlertDialogOpen129] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen130, setIsToolDuplicateConfirmDialogAlertDialogOpen130] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen131, setIsToolDuplicateConfirmDialogAlertDialogOpen131] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen132, setIsToolDuplicateConfirmDialogAlertDialogOpen132] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen133, setIsToolDuplicateConfirmDialogAlertDialogOpen133] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen134, setIsToolDuplicateConfirmDialogAlertDialogOpen134] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen135, setIsToolDuplicateConfirmDialogAlertDialogOpen135] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen136, setIsToolDuplicateConfirmDialogAlertDialogOpen136] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen137, setIsToolDuplicateConfirmDialogAlertDialogOpen137] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen138, setIsToolDuplicateConfirmDialogAlertDialogOpen138] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen139, setIsToolDuplicateConfirmDialogAlertDialogOpen139] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen140, setIsToolDuplicateConfirmDialogAlertDialogOpen140] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen141, setIsToolDuplicateConfirmDialogAlertDialogOpen141] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen142, setIsToolDuplicateConfirmDialogAlertDialogOpen142] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen143, setIsToolDuplicateConfirmDialogAlertDialogOpen143] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen144, setIsToolDuplicateConfirmDialogAlertDialogOpen144] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen145, setIsToolDuplicateConfirmDialogAlertDialogOpen145] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen146, setIsToolDuplicateConfirmDialogAlertDialogOpen146] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen147, setIsToolDuplicateConfirmDialogAlertDialogOpen147] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen148, setIsToolDuplicateConfirmDialogAlertDialogOpen148] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen149, setIsToolDuplicateConfirmDialogAlertDialogOpen149] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen150, setIsToolDuplicateConfirmDialogAlertDialogOpen150] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen151, setIsToolDuplicateConfirmDialogAlertDialogOpen151] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen152, setIsToolDuplicateConfirmDialogAlertDialogOpen152] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen153, setIsToolDuplicateConfirmDialogAlertDialogOpen153] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen154, setIsToolDuplicateConfirmDialogAlertDialogOpen154] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen155, setIsToolDuplicateConfirmDialogAlertDialogOpen155] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen156, setIsToolDuplicateConfirmDialogAlertDialogOpen156] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen157, setIsToolDuplicateConfirmDialogAlertDialogOpen157] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen158, setIsToolDuplicateConfirmDialogAlertDialogOpen158] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen159, setIsToolDuplicateConfirmDialogAlertDialogOpen159] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen160, setIsToolDuplicateConfirmDialogAlertDialogOpen160] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen161, setIsToolDuplicateConfirmDialogAlertDialogOpen161] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen162, setIsToolDuplicateConfirmDialogAlertDialogOpen162] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen163, setIsToolDuplicateConfirmDialogAlertDialogOpen163] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen164, setIsToolDuplicateConfirmDialogAlertDialogOpen164] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen165, setIsToolDuplicateConfirmDialogAlertDialogOpen165] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen166, setIsToolDuplicateConfirmDialogAlertDialogOpen166] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen167, setIsToolDuplicateConfirmDialogAlertDialogOpen167] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen168, setIsToolDuplicateConfirmDialogAlertDialogOpen168] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen169, setIsToolDuplicateConfirmDialogAlertDialogOpen169] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen170, setIsToolDuplicateConfirmDialogAlertDialogOpen170] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen171, setIsToolDuplicateConfirmDialogAlertDialogOpen171] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen172, setIsToolDuplicateConfirmDialogAlertDialogOpen172] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen173, setIsToolDuplicateConfirmDialogAlertDialogOpen173] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen174, setIsToolDuplicateConfirmDialogAlertDialogOpen174] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen175, setIsToolDuplicateConfirmDialogAlertDialogOpen175] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen176, setIsToolDuplicateConfirmDialogAlertDialogOpen176] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen177, setIsToolDuplicateConfirmDialogAlertDialogOpen177] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen178, setIsToolDuplicateConfirmDialogAlertDialogOpen178] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen179, setIsToolDuplicateConfirmDialogAlertDialogOpen179] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen180, setIsToolDuplicateConfirmDialogAlertDialogOpen180] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen181, setIsToolDuplicateConfirmDialogAlertDialogOpen181] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen182, setIsToolDuplicateConfirmDialogAlertDialogOpen182] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen183, setIsToolDuplicateConfirmDialogAlertDialogOpen183] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen184, setIsToolDuplicateConfirmDialogAlertDialogOpen184] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen185, setIsToolDuplicateConfirmDialogAlertDialogOpen185] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen186, setIsToolDuplicateConfirmDialogAlertDialogOpen186] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen187, setIsToolDuplicateConfirmDialogAlertDialogOpen187] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen188, setIsToolDuplicateConfirmDialogAlertDialogOpen188] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen189, setIsToolDuplicateConfirmDialogAlertDialogOpen189] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen190, setIsToolDuplicateConfirmDialogAlertDialogOpen190] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen191, setIsToolDuplicateConfirmDialogAlertDialogOpen191] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen192, setIsToolDuplicateConfirmDialogAlertDialogOpen192] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen193, setIsToolDuplicateConfirmDialogAlertDialogOpen193] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen194, setIsToolDuplicateConfirmDialogAlertDialogOpen194] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen195, setIsToolDuplicateConfirmDialogAlertDialogOpen195] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen196, setIsToolDuplicateConfirmDialogAlertDialogOpen196] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen197, setIsToolDuplicateConfirmDialogAlertDialogOpen197] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen198, setIsToolDuplicateConfirmDialogAlertDialogOpen198] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen199, setIsToolDuplicateConfirmDialogAlertDialogOpen199] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen200, setIsToolDuplicateConfirmDialogAlertDialogOpen200] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen201, setIsToolDuplicateConfirmDialogAlertDialogOpen201] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen202, setIsToolDuplicateConfirmDialogAlertDialogOpen202] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen203, setIsToolDuplicateConfirmDialogAlertDialogOpen203] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen204, setIsToolDuplicateConfirmDialogAlertDialogOpen204] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen205, setIsToolDuplicateConfirmDialogAlertDialogOpen205] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen206, setIsToolDuplicateConfirmDialogAlertDialogOpen206] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen207, setIsToolDuplicateConfirmDialogAlertDialogOpen207] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen208, setIsToolDuplicateConfirmDialogAlertDialogOpen208] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen209, setIsToolDuplicateConfirmDialogAlertDialogOpen209] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen210, setIsToolDuplicateConfirmDialogAlertDialogOpen210] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen211, setIsToolDuplicateConfirmDialogAlertDialogOpen211] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen212, setIsToolDuplicateConfirmDialogAlertDialogOpen212] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen213, setIsToolDuplicateConfirmDialogAlertDialogOpen213] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen214, setIsToolDuplicateConfirmDialogAlertDialogOpen214] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen215, setIsToolDuplicateConfirmDialogAlertDialogOpen215] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen216, setIsToolDuplicateConfirmDialogAlertDialogOpen216] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen217, setIsToolDuplicateConfirmDialogAlertDialogOpen217] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen218, setIsToolDuplicateConfirmDialogAlertDialogOpen218] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen219, setIsToolDuplicateConfirmDialogAlertDialogOpen219] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen220, setIsToolDuplicateConfirmDialogAlertDialogOpen220] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen221, setIsToolDuplicateConfirmDialogAlertDialogOpen221] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen222, setIsToolDuplicateConfirmDialogAlertDialogOpen222] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen223, setIsToolDuplicateConfirmDialogAlertDialogOpen223] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen224, setIsToolDuplicateConfirmDialogAlertDialogOpen224] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen225, setIsToolDuplicateConfirmDialogAlertDialogOpen2
