import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
import { Home, Settings, Bell, PieChart, UserPlus, CalendarPlus, Users, Calendar, BarChart2, Loader2, Send, Check, LogOut, ChevronDown, ChevronUp, Share2, FileEdit, Clock, AlertCircle, FileText, Eye, Plus, Target, ClipboardCheck, BookOpen, Trophy, Menu, MessageCircle } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { ScrollArea } from "@/components/ui/scroll-area";
import { supabase } from '@/lib/supabase';
import { useToast } from '@/hooks/use-toast';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { format, startOfMonth, endOfMonth, subMonths, isBefore, isAfter, isSameDay, isPast, formatDistance } from 'date-fns';
import { he } from 'date-fns/locale';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { SessionSummaryForm } from "@/components/session/SessionSummaryForm";
import { Calendar as CalendarComponent } from '@/components/calendar/Calendar';
import { Link } from 'react-router-dom';
import { Wrench } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Tool } from '@/types/tool';
import AllMeetingSummaries from './AllMeetingSummaries';
import { SessionFormDialog } from '@/components/sessions/SessionFormDialog';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Film } from 'lucide-react';
import { AdminMessageForm } from '@/components/admin/AdminMessageForm';
import { LandingPageDialog } from "@/components/landing-page/LandingPageDialog";
import { ClipboardList } from 'lucide-react';
import { useIsMobile } from '@/hooks/use-mobile';
import { useScreenSize } from '@/hooks/use-screen-size';

const DashboardCoach = () => {
  const navigate = useNavigate();
  const [coach, setCoach] = useState(null);
  const [tools, setTools] = useState<Tool[]>([]);
  const [sessions, setSessions] = useState([]);
  const [upcomingSessions, setUpcomingSessions] = useState([]);
  const [playersCount, setPlayersCount] = useState(0);
  const [showAllTools, setShowAllTools] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [isNotificationsOpen, setIsNotificationsOpen] = useState(false);
  const [isShareOpen, setIsShareOpen] = useState(false);
  const [isProfileOpen, setIsProfileOpen] = useState(false);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isCollapsibleOpen, setIsCollapsibleOpen] = useState(false);
  const [isLandingPageDialogOpen, setIsLandingPageDialogOpen] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isNewSessionDialogOpen, setIsNewSessionDialogOpen] = useState(false);
  const [isAllSummariesOpen, setIsAllSummariesOpen] = useState(false);
  const [isNewMessageDialogOpen, setIsNewMessageDialogOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const [windowSize, setWindowSize] = useState({ width: 0, height: 0 });
  const [isAlertOpen, setIsAlertOpen] = useState(false);
  const [alertMessage, setAlertMessage] = useState('');
  const [alertTitle, setAlertTitle] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [events, setEvents] = useState([]);
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [currentMonth, setCurrentMonth] = useState(startOfMonth(new Date()));
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isSessionSummaryDialogOpen, setIsSessionSummaryDialogOpen] = useState(false);
  const [sessionForSummary, setSessionForSummary] = useState(null);
  const [isSessionFormDialogOpen, setIsSessionFormDialogOpen] = useState(false);
  const [isToolDialogOpen, setIsToolDialogOpen] = useState(false);
  const [selectedTool, setSelectedTool] = useState(null);
  const [isToolEditMode, setIsToolEditMode] useState(false);
  const [isToolDeleteAlertOpen, setIsToolDeleteAlertOpen] = useState(false);
  const [toolToDelete, setToolToDelete] = useState(null);
  const [isToolShareDialogOpen, setIsToolShareDialogOpen] = useState(false);
  const [toolToShare, setToolToShare] = useState(null);
  const [isToolDetailsDialogOpen, setIsToolDetailsDialogOpen] = useState(false);
  const [toolForDetails, setToolForDetails] = useState(null);
  const [isToolCreateDialogOpen, setIsToolCreateDialogOpen] = useState(false);
  const [isToolEditDialogOpen, setIsToolEditDialogOpen] = useState(false);
  const [isToolDeleteDialogOpen, setIsToolDeleteDialogOpen] = useState(false);
  const [isToolDuplicateDialogOpen, setIsToolDuplicateDialogOpen] = useState(false);
  const [toolToDuplicate, setToolToDuplicate] = useState(null);
  const [isToolDuplicateAlertOpen, setIsToolDuplicateAlertOpen] = useState(false);
  const [isToolDuplicateConfirmOpen, setIsToolDuplicateConfirmOpen] = useState(false);
  const [isToolDuplicateConfirmAlertOpen, setIsToolDuplicateConfirmAlertOpen] = useState(false);
  const [isToolDuplicateConfirmDialogOpen, setIsToolDuplicateConfirmDialogOpen] = useState(false);
  const [isToolDuplicateConfirmDialogAlertOpen, setIsToolDuplicateConfirmDialogAlertOpen] = useState(false);
  const [isToolDuplicateConfirmDialogDialogOpen, setIsToolDuplicateConfirmDialogDialogOpen] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen, setIsToolDuplicateConfirmDialogAlertOpen] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen2, setIsToolDuplicateConfirmDialogAlertOpen2] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen3, setIsToolDuplicateConfirmDialogAlertOpen3] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen4, setIsToolDuplicateConfirmDialogAlertOpen4] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen5, setIsToolDuplicateConfirmDialogAlertOpen5] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen6, setIsToolDuplicateConfirmDialogAlertOpen6] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen7, setIsToolDuplicateConfirmDialogAlertOpen7] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen8, setIsToolDuplicateConfirmDialogAlertOpen8] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen9, setIsToolDuplicateConfirmDialogAlertOpen9] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen10, setIsToolDuplicateConfirmDialogAlertOpen10] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen11, setIsToolDuplicateConfirmDialogAlertOpen11] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen12, setIsToolDuplicateConfirmDialogAlertOpen12] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen13, setIsToolDuplicateConfirmDialogAlertOpen13] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen14, setIsToolDuplicateConfirmDialogAlertOpen14] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen15, setIsToolDuplicateConfirmDialogAlertOpen15] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen16, setIsToolDuplicateConfirmDialogAlertOpen16] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen17, setIsToolDuplicateConfirmDialogAlertOpen17] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen18, setIsToolDuplicateConfirmDialogAlertOpen18] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen19, setIsToolDuplicateConfirmDialogAlertOpen19] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen20, setIsToolDuplicateConfirmDialogAlertOpen20] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen21, setIsToolDuplicateConfirmDialogAlertOpen21] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen22, setIsToolDuplicateConfirmDialogAlertOpen22] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen23, setIsToolDuplicateConfirmDialogAlertOpen23] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen24, setIsToolDuplicateConfirmDialogAlertOpen24] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen25, setIsToolDuplicateConfirmDialogAlertOpen25] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen26, setIsToolDuplicateConfirmDialogAlertOpen26] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen27, setIsToolDuplicateConfirmDialogAlertOpen27] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen28, setIsToolDuplicateConfirmDialogAlertOpen28] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen29, setIsToolDuplicateConfirmDialogAlertOpen29] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen30, setIsToolDuplicateConfirmDialogAlertOpen30] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen31, setIsToolDuplicateConfirmDialogAlertOpen31] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen32, setIsToolDuplicateConfirmDialogAlertOpen32] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen33, setIsToolDuplicateConfirmDialogAlertOpen33] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen34, setIsToolDuplicateConfirmDialogAlertOpen34] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen35, setIsToolDuplicateConfirmDialogAlertOpen35] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen36, setIsToolDuplicateConfirmDialogAlertOpen36] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen37, setIsToolDuplicateConfirmDialogAlertOpen37] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen38, setIsToolDuplicateConfirmDialogAlertOpen38] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen39, setIsToolDuplicateConfirmDialogAlertOpen39] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen40, setIsToolDuplicateConfirmDialogAlertOpen40] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen41, setIsToolDuplicateConfirmDialogAlertOpen41] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen42, setIsToolDuplicateConfirmDialogAlertOpen42] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen43, setIsToolDuplicateConfirmDialogAlertOpen43] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen44, setIsToolDuplicateConfirmDialogAlertOpen44] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen45, setIsToolDuplicateConfirmDialogAlertOpen45] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen46, setIsToolDuplicateConfirmDialogAlertOpen46] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen47, setIsToolDuplicateConfirmDialogAlertOpen47] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen48, setIsToolDuplicateConfirmDialogAlertOpen48] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen49, setIsToolDuplicateConfirmDialogAlertOpen49] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen50, setIsToolDuplicateConfirmDialogAlertOpen50] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen51, setIsToolDuplicateConfirmDialogAlertOpen51] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen52, setIsToolDuplicateConfirmDialogAlertOpen52] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen53, setIsToolDuplicateConfirmDialogAlertOpen53] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen54, setIsToolDuplicateConfirmDialogAlertOpen54] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen55, setIsToolDuplicateConfirmDialogAlertOpen55] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen56, setIsToolDuplicateConfirmDialogAlertOpen56] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen57, setIsToolDuplicateConfirmDialogAlertOpen57] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen58, setIsToolDuplicateConfirmDialogAlertOpen58] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen59, setIsToolDuplicateConfirmDialogAlertOpen59] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen60, setIsToolDuplicateConfirmDialogAlertOpen60] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen61, setIsToolDuplicateConfirmDialogAlertOpen61] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen62, setIsToolDuplicateConfirmDialogAlertOpen62] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen63, setIsToolDuplicateConfirmDialogAlertOpen63] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen64, setIsToolDuplicateConfirmDialogAlertOpen64] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen65, setIsToolDuplicateConfirmDialogAlertOpen65] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen66, setIsToolDuplicateConfirmDialogAlertOpen66] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen67, setIsToolDuplicateConfirmDialogAlertOpen67] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen68, setIsToolDuplicateConfirmDialogAlertOpen68] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen69, setIsToolDuplicateConfirmDialogAlertOpen69] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen70, setIsToolDuplicateConfirmDialogAlertOpen70] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen71, setIsToolDuplicateConfirmDialogAlertOpen71] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen72, setIsToolDuplicateConfirmDialogAlertOpen72] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen73, setIsToolDuplicateConfirmDialogAlertOpen73] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen74, setIsToolDuplicateConfirmDialogAlertDialogOpen74] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen75, setIsToolDuplicateConfirmDialogAlertOpen75] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen76, setIsToolDuplicateConfirmDialogAlertOpen76] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen77, setIsToolDuplicateConfirmDialogAlertOpen77] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen78, setIsToolDuplicateConfirmDialogAlertOpen78] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen79, setIsToolDuplicateConfirmDialogAlertOpen79] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen80, setIsToolDuplicateConfirmDialogAlertOpen80] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen81, setIsToolDuplicateConfirmDialogAlertOpen81] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen82, setIsToolDuplicateConfirmDialogAlertOpen82] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen83, setIsToolDuplicateConfirmDialogAlertOpen83] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen84, setIsToolDuplicateConfirmDialogAlertOpen84] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen85, setIsToolDuplicateConfirmDialogAlertOpen85] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen86, setIsToolDuplicateConfirmDialogAlertOpen86] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen87, setIsToolDuplicateConfirmDialogAlertOpen87] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen88, setIsToolDuplicateConfirmDialogAlertOpen88] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen89, setIsToolDuplicateConfirmDialogAlertOpen89] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen90, setIsToolDuplicateConfirmDialogAlertOpen90] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen91, setIsToolDuplicateConfirmDialogAlertOpen91] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen92, setIsToolDuplicateConfirmDialogAlertDialogOpen92] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen93, setIsToolDuplicateConfirmDialogAlertOpen93] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen94, setIsToolDuplicateConfirmDialogAlertOpen94] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen95, setIsToolDuplicateConfirmDialogAlertOpen95] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen96, setIsToolDuplicateConfirmDialogAlertOpen96] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen97, setIsToolDuplicateConfirmDialogAlertOpen97] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen98, setIsToolDuplicateConfirmDialogAlertOpen98] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen99, setIsToolDuplicateConfirmDialogAlertOpen99] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen100, setIsToolDuplicateConfirmDialogAlertOpen100] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen101, setIsToolDuplicateConfirmDialogAlertOpen101] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen102, setIsToolDuplicateConfirmDialogAlertOpen102] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen103, setIsToolDuplicateConfirmDialogAlertOpen103] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen104, setIsToolDuplicateConfirmDialogAlertOpen104] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen105, setIsToolDuplicateConfirmDialogAlertOpen105] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen106, setIsToolDuplicateConfirmDialogAlertOpen106] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen107, setIsToolDuplicateConfirmDialogAlertOpen107] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen108, setIsToolDuplicateConfirmDialogAlertOpen108] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen109, setIsToolDuplicateConfirmDialogAlertOpen109] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen110, setIsToolDuplicateConfirmDialogAlertOpen110] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen111, setIsToolDuplicateConfirmDialogAlertOpen111] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen112, setIsToolDuplicateConfirmDialogAlertOpen112] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen113, setIsToolDuplicateConfirmDialogAlertOpen113] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen114, setIsToolDuplicateConfirmDialogAlertOpen114] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen115, setIsToolDuplicateConfirmDialogAlertOpen115] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen116, setIsToolDuplicateConfirmDialogAlertOpen116] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen117, setIsToolDuplicateConfirmDialogAlertOpen117] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen118, setIsToolDuplicateConfirmDialogAlertOpen118] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen119, setIsToolDuplicateConfirmDialogAlertOpen119] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen120, setIsToolDuplicateConfirmDialogAlertOpen120] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen121, setIsToolDuplicateConfirmDialogAlertOpen121] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen122, setIsToolDuplicateConfirmDialogAlertOpen122] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen123, setIsToolDuplicateConfirmDialogAlertOpen123] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen124, setIsToolDuplicateConfirmDialogAlertOpen124] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen125, setIsToolDuplicateConfirmDialogAlertOpen125] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen126, setIsToolDuplicateConfirmDialogAlertOpen126] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen127, setIsToolDuplicateConfirmDialogAlertOpen127] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen128, setIsToolDuplicateConfirmDialogAlertOpen128] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen129, setIsToolDuplicateConfirmDialogAlertOpen129] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen130, setIsToolDuplicateConfirmDialogAlertOpen130] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen131, setIsToolDuplicateConfirmDialogAlertOpen131] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen132, setIsToolDuplicateConfirmDialogAlertOpen132] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen133, setIsToolDuplicateConfirmDialogAlertOpen133] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen134, setIsToolDuplicateConfirmDialogAlertOpen134] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen135, setIsToolDuplicateConfirmDialogAlertOpen135] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen136, setIsToolDuplicateConfirmDialogAlertOpen136] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen137, setIsToolDuplicateConfirmDialogAlertOpen137] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen138, setIsToolDuplicateConfirmDialogAlertOpen138] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen139, setIsToolDuplicateConfirmDialogAlertOpen139] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen140, setIsToolDuplicateConfirmDialogAlertOpen140] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen141, setIsToolDuplicateConfirmDialogAlertOpen141] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen142, setIsToolDuplicateConfirmDialogAlertOpen142] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen143, setIsToolDuplicateConfirmDialogAlertOpen143] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen144, setIsToolDuplicateConfirmDialogAlertOpen144] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen145, setIsToolDuplicateConfirmDialogAlertOpen145] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen146, setIsToolDuplicateConfirmDialogAlertOpen146] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen147, setIsToolDuplicateConfirmDialogAlertOpen147] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen148, setIsToolDuplicateConfirmDialogAlertOpen148] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen149, setIsToolDuplicateConfirmDialogAlertOpen149] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen150, setIsToolDuplicateConfirmDialogAlertOpen150] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen151, setIsToolDuplicateConfirmDialogAlertOpen151] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen152, setIsToolDuplicateConfirmDialogAlertOpen152] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen153, setIsToolDuplicateConfirmDialogAlertOpen153] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen154, setIsToolDuplicateConfirmDialogAlertOpen154] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen155, setIsToolDuplicateConfirmDialogAlertOpen155] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen156, setIsToolDuplicateConfirmDialogAlertOpen156] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen157, setIsToolDuplicateConfirmDialogAlertOpen157] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen158, setIsToolDuplicateConfirmDialogAlertOpen158] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen159, setIsToolDuplicateConfirmDialogAlertOpen159] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen160, setIsToolDuplicateConfirmDialogAlertOpen160] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen161, setIsToolDuplicateConfirmDialogAlertOpen161] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen162, setIsToolDuplicateConfirmDialogAlertOpen162] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen163, setIsToolDuplicateConfirmDialogAlertOpen163] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen164, setIsToolDuplicateConfirmDialogAlertOpen164] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen165, setIsToolDuplicateConfirmDialogAlertOpen165] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen166, setIsToolDuplicateConfirmDialogAlertOpen166] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen167, setIsToolDuplicateConfirmDialogAlertOpen167] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen168, setIsToolDuplicateConfirmDialogAlertOpen168] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen169, setIsToolDuplicateConfirmDialogAlertOpen169] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen170, setIsToolDuplicateConfirmDialogAlertOpen170] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen171, setIsToolDuplicateConfirmDialogAlertOpen171] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen172, setIsToolDuplicateConfirmDialogAlertOpen172] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen173, setIsToolDuplicateConfirmDialogAlertOpen173] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen174, setIsToolDuplicateConfirmDialogAlertOpen174] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen175, setIsToolDuplicateConfirmDialogAlertOpen175] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen176, setIsToolDuplicateConfirmDialogAlertOpen176] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen177, setIsToolDuplicateConfirmDialogAlertOpen177] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen178, setIsToolDuplicateConfirmDialogAlertOpen178] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen179, setIsToolDuplicateConfirmDialogAlertOpen179] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen180, setIsToolDuplicateConfirmDialogAlertOpen180] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen181, setIsToolDuplicateConfirmDialogAlertOpen181] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen182, setIsToolDuplicateConfirmDialogAlertOpen182] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen183, setIsToolDuplicateConfirmDialogAlertOpen183] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen184, setIsToolDuplicateConfirmDialogAlertOpen184] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen185, setIsToolDuplicateConfirmDialogAlertOpen185] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen186, setIsToolDuplicateConfirmDialogAlertOpen186] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen187, setIsToolDuplicateConfirmDialogAlertOpen187] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen188, setIsToolDuplicateConfirmDialogAlertOpen188] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen189, setIsToolDuplicateConfirmDialogAlertOpen189] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen190, setIsToolDuplicateConfirmDialogAlertOpen190] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen191, setIsToolDuplicateConfirmDialogAlertOpen191] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen192, setIsToolDuplicateConfirmDialogAlertOpen192] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen193, setIsToolDuplicateConfirmDialogAlertOpen193] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen194, setIsToolDuplicateConfirmDialogAlertOpen194] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen195, setIsToolDuplicateConfirmDialogAlertOpen195] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen196, setIsToolDuplicateConfirmDialogAlertOpen196] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen197, setIsToolDuplicateConfirmDialogAlertOpen197] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen198, setIsToolDuplicateConfirmDialogAlertOpen198] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen199, setIsToolDuplicateConfirmDialogAlertOpen199] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen200, setIsToolDuplicateConfirmDialogAlertOpen200] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen201, setIsToolDuplicateConfirmDialogAlertOpen201] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen202, setIsToolDuplicateConfirmDialogAlertOpen202] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen203, setIsToolDuplicateConfirmDialogAlertOpen203] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen204, setIsToolDuplicateConfirmDialogAlertOpen204] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen205, setIsToolDuplicateConfirmDialogAlertOpen205] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen206, setIsToolDuplicateConfirmDialogAlertOpen206] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen207, setIsToolDuplicateConfirmDialogAlertOpen207] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen208, setIsToolDuplicateConfirmDialogAlertOpen208] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen209, setIsToolDuplicateConfirmDialogAlertOpen209] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen210, setIsToolDuplicateConfirmDialogAlertOpen210] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen211, setIsToolDuplicateConfirmDialogAlertOpen211] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen212, setIsToolDuplicateConfirmDialogAlertOpen212] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen213, setIsToolDuplicateConfirmDialogAlertOpen213] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen214, setIsToolDuplicateConfirmDialogAlertOpen214] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen215, setIsToolDuplicateConfirmDialogAlertOpen215] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen216, setIsToolDuplicateConfirmDialogAlertOpen216] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen217, setIsToolDuplicateConfirmDialogAlertOpen217] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen218, setIsToolDuplicateConfirmDialogAlertOpen218] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen219, setIsToolDuplicateConfirmDialogAlertOpen219] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen220, setIsToolDuplicateConfirmDialogAlertOpen220] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen221, setIsToolDuplicateConfirmDialogAlertOpen221] = useState(false);
  const [isToolDuplicateConfirmDialogAlertDialogOpen222, setIsToolDuplicateConfirmDialogAlert
